spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://panyusql.mysql.database.azure.com:3306/graduation
    username: truman
    password: Fyh.mysql20000718
  mail:
    username: TrumanVon@126.com
    host: smtp.126.com
    password: EASSCRMQKCQWZTJW
    protocol: smtp
    port: 25
  redis:
    host: panyu-cache.redis.cache.windows.net
    password: UHPEGF9EuoR48WDD8b4VgPzEe4B12ybeVAzCaJYmWwk=
    database: 0
  mvc:
    static-path-pattern: /**

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:log/logback.xml
